export const ADD_TODO = 'add_todo'
export const DELETE_TODO = 'delete_todo'
export const SELECT_ALL = 'select_all'
export const DELETE_COMPLETE_TODOS = 'delete_all_complete'
export const DELETE_ITEM = 'delete_item'
export const RECEIVE_TODOS = 'receive_todos'
